##### --- CONFIGURACIÓN GENERAL ---
set -g base-index 1
setw -g pane-base-index 1
set -g mouse on
set -sg escape-time 0
set -g default-terminal "screen-256color"
set-option -g allow-rename off
set -g history-limit 10000

##### --- ATAJOS DIRECTOS ---
bind -n F2 next-window
bind -n F3 previous-window
bind -n F4 select-window -t 1
bind -n F5 select-window -t 2
bind -n F6 select-window -t 3
bind -n F7 new-window
bind -n F8 kill-window

# Recargar con F9
bind -n F9 source-file ~/.tmux.conf \; display-message "Configuración recargada"

##### --- INICIAR ENTORNO (Alt + i) ---
# Usa la ruta exacta: ~/JLimbhert/Jroot

bind -n M-i \
    rename-window -t 1 'Jroot' \; \
    send-keys -t 1 'cd ~/JLimbhert/Jroot && clear' C-m \; \
    new-window -t 2 -n 'NVIM' \; \
    send-keys -t 2 'cd ~/JLimbhert/Jroot && nvim' C-m \; \
    new-window -t 3 -n 'RANGER' \; \
    send-keys -t 3 'cd ~/JLimbhert/Jroot && ranger' C-m \; \
    select-window -t 1

##### --- DISEÑO PERSONALIZADO (Dark Red & Deep Grey) ---

# Color de fondo de la barra principal (Gris oscuro 16,16,16)
set -g status-style bg='#101010',fg=white

# Lado izquierdo: Nombre de la sesión en rojo oscuro
set -g status-left "#[fg=#8b0000,bold,bg=#101010]  #S #[fg=#101010,bg=default] "

# Ventanas inactivas (Gris suave)
setw -g window-status-style fg='#666666',bg='#101010'
setw -g window-status-format " #I:#W "

# VENTANA ACTIVA (Dark Red con texto blanco/claro)
# Aquí es donde resalta la ventana de NVIM o Jroot cuando estás en ella
setw -g window-status-current-style fg=white,bold,bg='#8b0000'
setw -g window-status-current-format " #I:#W "

# Lado derecho: Fecha y hora con toques de rojo
set -g status-right-length 50
set -g status-right "#[fg=#666666]%d-%b #[fg=#8b0000]| #[fg=white,bold]%H:%M "

# Bordes de los paneles (si llegas a dividir la pantalla)
set -g pane-border-style fg='#101010'
set -g pane-active-border-style fg='#8b0000'

# Mensajes de tmux (el que sale al presionar F9)
set -g message-style bg='#8b0000',fg=white,bold

